music/urls.py
from django.conf.urls import url
from . import nviews,views
app_name = 'music'
urlpatterns = [
	# /music/
    #url(r'^$', views.index, name = 'index'),
    url(r'^$', nviews.IndexView.as_view(), name = 'index'),

    # /register/
    url(r'^register/$', nviews.UserFormView.as_view(), name = 'register'),

    # /music/album_id
    #rl(r'^(?P<album_id>[0-9]+)/$', views.detail, name= "detail"),

    # /music/album_id
    url(r'^(?P<pk>[0-9]+)/$', nviews.DetailView.as_view(), name= "detail"),

    #/music/album_id/favourite  to  /music/album_id
    url(r'^(?P<album_id>[0-9]+)/favourite$', nviews.favourite, name= "favourite"),

    # /music/album/add
    url(r'^album/add$',nviews.AlbumCreate.as_view(), name = 'add_album'),

    # /music/album/album_id/
    url(r'^album/(?P<pk>[0-9]+)/$',nviews.AlbumUpdate.as_view(), name = 'update_album'),

    # /music/album/album_id/delete
    url(r'^album/(?P<pk>[0-9]+)/delete/$',nviews.AlbumDelete.as_view(), name = 'delete_album'),

    # /music/album_id/song/add
    url(r'^song/add/$',nviews.SongCreate.as_view(), name= 'add_song'),

    # /music/album_id/song/song_id/
    url(r'^song/(?P<pk>[0-9]+)/$',nviews.SongUpdate.as_view(), name='update_song'),

    # /music/album_id/song/song_id/delete
    url(r'^song/(?P<pk>[0-9]+)/delete$',nviews.SongDelete.as_view(), name='delete_song'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import views

urlpatterns = [
    #url(r'^home/', include('home.urls')),
    url(r'^$', views.home,name='Home'),
    url(r'^admin/', admin.site.urls,name='admin_database'),
    url(r'^music/', include('music.urls'),name='music_site'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models


class Album(models.Model):
	artist = models.CharField(max_length = 250)
	album_title  = models.CharField(max_length = 500)
	genre  = models.CharField(max_length = 100)
	album_logo  = models.FileField()
	#logo_path = models.CharField(max_length = 5000)

	def get_absolute_url(self):
		#return reverse("detail" , kwargs={ "pk" : self.id})
		return '/music/%i/' %self.id

	def __str__(self):
		return self.album_title + ' :- ' + self.artist 
class Song(models.Model):
	album = models.ForeignKey(Album , on_delete=models.CASCADE)
	file_type  = models.CharField(max_length = 10)
	song_title  = models.CharField(max_length = 250)
	is_favourite = models.BooleanField(default=False)
	song_path = models.FileField()

	def get_absolute_url(self):
		return '/music/%i/' %self.album.id

	def __str__(self):
		return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username' , 'email', 'password' ]

music/views.py
#from django.http import HttpResponse
#from django.http import Http404
from .models import Album,Song
from django.views import generic
from django.shortcuts import render,get_object_or_404
from django.views.generic.edit import CreateView,UpdateView,DeleteView
#from django.template import loader

def index(request):
	all_albums = Album.objects.all()
	#template = loader.get_template('music/index.html')
	context = {
		'all_albums':all_albums,
	}
	#return HttpResponse(template.render(context,request))
	return render(request,'music/index.html',context)

def detail(request, album_id):
	album = get_object_or_404(Album,pk =album_id)
	#return HttpResponse(template.render(context, request))
	return render(request, 'music/Details.html', {'album' : album })
	#return HttpResponse("<title>Details</title><h1>Details for album_id :"+str(album_id)+"</h1>")

def favourite(request, album_id):
	album = get_object_or_404(Album,pk =album_id)
	try:
		selected_song = album.song_set.get(pk = request.POST['song'])
	except (KeyError, Song.DoesNotExist):
		return render(request, 'music/Details.html',
				  {'album' : album ,
				'error_message' : "you did not select a valid song or there is no song in this album"}
					  )
	else:
		selected_song.is_favourite = True
		selected_song.save()
		return render(request, 'music/Details.html', {'album': album})

class AlbumCreate(CreateView):
	model = Album
	fields = ['artist','album_title', 'genre' , 'album_logo' ,'logo_path']

mysite/views.py
from django.shortcuts import render,get_object_or_404,render_to_response
from django.http import HttpResponse

def home(request):
    html = " <h1>Welcome to my Home Page</h1><ol><li><a href='/music/'>To go to Music page</a></li><li><a href='/admin/'>To go to admin page</a></li></ol>"
    #return render(request, 'mysite/home.html',context=None)
    return HttpResponse(html)
    #return render_to_response('mysite/home.html')

music/templates/music/Details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'music/style.css' %}" type="text/css">
    <img src="{{ album.album_logo.url }} " alt="{{ album.album_logo }}" width="1000" height="500">

    <h1>Album Title : <i>{{ album.album_title}}</i></h1>
    <h2>Album Artist : {{ album.artist }}</h2>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
     {% for song in album.song_set.all %}
    <form action="{% url 'music:favourite' album.id %} " method="post">
        {% csrf_token %}
            <input type="checkbox" name="song" id="song{{ forloop.counter }}" value ="{{ song.id }}">
            <label for="song{{ forloop.counter }}">
                {{ song.song_title }}
                {% if song.is_favourite %}
                    <img src="http://megaicons.net/static/img/icons_sizes/51/1538/256/favourites-star-sh-icon.png" height="16" width="16">
                {% endif %}
                <audio controls src="{{ song.song_path.url }}" >  </audio>
            </label>
            <br>

        <input type="submit" value="Favourite">
    </form>
         <br>
        <form action="{% url 'music:delete_song' song.id %} " method="post" style="display: inline;">
            {% csrf_token %}
                <input type="hidden" name="song_id" value="{{ song.id }}">
                <button type="submit" style="height:25px; width:60px " >Delete
                </button>

        </form>
            <form action="{% url 'music:update_song' song.id %} " method="post" style="display: inline;">
            {% csrf_token %}
                <input type="hidden" name="song_id" value="{{ song.id }}">
                <button type="submit" style="height:25px; width:60px">Update
                </button>

        </form>

     {% endfor %}
    <h5></h5>
    <div>
        <form action="{% url 'music:add_song' %} " style="display: inline;">
            {% csrf_token %}
                <button type="submit" style="height:25px; width:100px">Add Song
                </button>

        </form>
    </div>
</body>
</html>

music/templates/music/album_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Your Album</title>
</head>
<body>
    <h3>Create a new Album</h3>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <span>{{ field.errors }}</span>
            <label>{{ field.label_tag }}</label>
            <div>{{ field }}</div>
        {% endfor %}
    <br>
        <button type="submit">Add Album</button>
    </form>
</body>
</html>

music/templates/music/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Music_Albums</title>
</head>
<body>
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'music/style.css' %}" type="text/css">

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'music:index' %}">Music Crazy </a>
        </div>
    </div>
</nav>
<h3><strong>Here My all Album Collections</strong></h3>
{% if all_albums %}
      <ol>  {% for album in all_albums %}
            <li>
            <div>
                <img src="{{ album.album_logo.url }} " alt="{{ album.album_logo }}" width="100" height="100">
            </div>
             <a href="{% url  'music:detail' album.id %} ">{{ album.album_title }}</a>
                <div>
        <form action="{% url 'music:delete_album' album.id %} " method="post" style="display: inline;">
            {% csrf_token %}
                <input type="hidden" name="album_id" value="{{ album.id }}">
                <button type="submit" style="height:25px; width:60px " >Delete
                </button>

        </form>
            <form action="{% url 'music:update_album' album.id %} " method="post" style="display: inline;">
            {% csrf_token %}
                <input type="hidden" name="album_id" value="{{ album.id }}">
                <button type="submit" style="height:25px; width:60px">Update
                </button>

        </form>
                </div>
            <br>
            </li>

        {% endfor %}

      </ol>
{% else %}
    <h1>You don't have any albums</h1>
{% endif %}
    <div>
        <form action="{% url 'music:add_album' %} " style="display: inline;">
            {% csrf_token %}
                <button type="submit" style="height:25px; width:100px">Add Album
                </button>
        </form>
    </div>
</body>
</html>

music/templates/music/registration_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register Form</title>
</head>
<body>
    <h3>Create a new User</h3>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <span>{{ field.errors }}</span>
            <label>{{ field.label_tag }}</label>
            <div>{{ field }}</div>
        {% endfor %}
    <br>
        <button type="submit">Add User</button>
    </form>
</body>
</html>

music/templates/music/song_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Song In This Album</title>
</head>
<body>
    <h3>Add a new Song</h3>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}

            <label>{{ field.label_tag }}</label>
            <span>{{ field.errors }}</span>
                <div>{{ field }}</div>

        {% endfor %}
    <br>
        <button type="submit">Add Song</button>
    </form>
</body>
</html>

mysite/templates/mysite/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
        <h1>Welcome to my Home Page</h1>
        <ol>
            <li><a href="{% url  'mysite:admin_database' %}"></a></li>
            <li><a href="{% url  'mysite:music_site' %}"></a></li>
        </ol>
</body>
</html>